config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "products#index"

  resources :products

  # get "up" => "rails/health#show", as: :rails_health_check
  # get "/products", to: "products#index"

  # get "/products/new", to: "products#new"
  # post "/products", to: "products#create"

  # get "/products/:id", to: "products#show"

  # get "/products/:id/edit", to: "products#edit"
  # patch "/products/:id", to: "products#update"
  # put "/products/:id", to: "products#update"

  # delete "/products/:id", to: "products#destroy"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

   def show
    @product = Product.find(params[:id])
   end

   def new
    @product = Product.new
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store Template" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Store Template">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="text-center mb-4">
  <h1 class="text-title">Products</h1>
  <%= link_to "✚ New product", new_product_path, class: "btn btn--primary" %>
</div>

<div class="products-grid">
  <% @products.each do |product| %>
    <div class="card">
      <div class="card-body">
        <h3 class="card-title"><%= product.name %></h3>

        <div class="flex gap-2 mt-3">
          <%= link_to "View details", product_path(product), class: "btn btn--primary btn--block" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="container--form">
  <div class="mb-4">
    <h1 class="text-subheading">New Product</h1>
  </div>

  <div class="card">
    <div class="card-body">
      <%= form_with model: @product do |form| %>

        <div class="form-group">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class: "form-control", placeholder: "Product name" %>
        </div>

        <div class="form-group">
          <%= form.submit class: "btn btn--primary btn--block" %>
        </div>
      <% end %>
    </div>

    <div class="card-footer">
      <%= link_to "← Cancel", products_path, class: "btn btn--sm" %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container--lg">
  <div class="mb-3">
    <%= link_to "← Volver a los productos", products_path, class: "link--secondary" %>
  </div>

  <div class="card">
    <div class="grid-2">
      <div class="card-body">
        <h1 class="text-title">
          <%= @product.name %>
        </h1>
      </div>
    </div>
  </div>
</div>